/**
 * Test Project — ESPAI Project Firmware
 *
 * Generated by ESPAI. Modify freely.
 * The node API endpoints (manifest/status/checkin/reboot/ota) are
 * inherited from the seed firmware — add your project logic below.
 */

#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <ArduinoJson.h>

#ifndef NODE_NAME
#define NODE_NAME "test-project"
#endif
#ifndef FW_VERSION
#define FW_VERSION "0.1.0"
#endif
#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif
#ifndef WIFI_PASS
#define WIFI_PASS ""
#endif
#ifndef BOARD_ID
#define BOARD_ID "esp32dev"
#endif

static const uint32_t WIFI_TIMEOUT_MS = 15000;

WebServer server(80);

// ── Node ID (hashed MAC) ──────────────────────────────────────────────────
#include <mbedtls/md.h>
String deriveNodeId() {
  uint8_t mac[6], hash[32];
  WiFi.macAddress(mac);
  mbedtls_md_context_t ctx;
  mbedtls_md_init(&ctx);
  mbedtls_md_setup(&ctx, mbedtls_md_info_from_type(MBEDTLS_MD_SHA256), 0);
  mbedtls_md_starts(&ctx);
  mbedtls_md_update(&ctx, mac, 6);
  mbedtls_md_finish(&ctx, hash);
  mbedtls_md_free(&ctx);
  String id = "node-";
  for (int i = 0; i < 6; i++) { if (hash[i] < 0x10) id += "0"; id += String(hash[i], HEX); }
  return id;
}

String nodeId;

void sendJson(int code, JsonDocument& doc) {
  String body; serializeJson(doc, body);
  server.send(code, "application/json", body);
}

void handleManifest() {
  JsonDocument doc;
  doc["schema"] = "ESPAI.device.v1";
  doc["id"]     = nodeId;
  doc["name"]   = NODE_NAME;
  doc["board"]  = BOARD_ID;
  doc["fw_version"] = FW_VERSION;
  JsonObject caps = doc["capabilities"].to<JsonObject>();
  caps["ota"] = true;
  sendJson(200, doc);
}

void handleStatus() {
  JsonDocument doc;
  doc["id"]       = nodeId;
  doc["uptime_s"] = millis() / 1000;
  doc["heap_free"]= ESP.getFreeHeap();
  doc["ip"]       = WiFi.localIP().toString();
  sendJson(200, doc);
}

// ── TODO: add your project endpoints here ─────────────────────────────────
// void handleSensorRead() { ... }

void setup() {
  Serial.begin(115200);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  uint32_t t = millis();
  while (WiFi.status() != WL_CONNECTED && millis()-t < WIFI_TIMEOUT_MS) delay(200);

  WiFi.mode(WIFI_STA);
  nodeId = deriveNodeId();
  Serial.printf("Node ID: %s  IP: %s\n", nodeId.c_str(), WiFi.localIP().toString().c_str());

  MDNS.begin(nodeId.c_str());
  MDNS.addService("_ESPAI-node", "_tcp", 80);

  server.on("/api/manifest", HTTP_GET,  handleManifest);
  server.on("/api/status",   HTTP_GET,  handleStatus);
  server.on("/api/reboot",   HTTP_POST, [](){ JsonDocument d; d["status"]="rebooting"; String b; serializeJson(d,b); server.send(200,"application/json",b); delay(200); ESP.restart(); });
  // TODO: register your project endpoints
  // server.on("/api/sensor", HTTP_GET, handleSensorRead);
  server.begin();
}

void loop() {
  server.handleClient();
  delay(1);
}
