import hashlib
import io
import json
import re
import secrets
import shutil
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import Path

import mimetypes

from fastapi import APIRouter, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import FileResponse
from pydantic import BaseModel, field_validator

from ..config import ACTIVE_THEME, DESIGN_DIR, FIRMWARE_CATALOG_DIR, PROJECTS_DIR
from ..db import get_conn, _to_hostname
from .. import git_helper
from ..discovery.mdns import mdns_manager as _mdns

router = APIRouter()

_SAFE_NAME = re.compile(r"[^\w\s\-\.]")  # strip unsafe chars from folder names


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class ProjectCreate(BaseModel):
    name: str
    description: str | None = None
    devices: list[str] = []

    @field_validator("name")
    @classmethod
    def name_is_valid_hostname(cls, v: str) -> str:
        """
        Project names double as mDNS hostnames — coerce to hostname-safe form
        on the way in so every downstream user (firmware, proxy URL, Caddy)
        gets a consistent slug without extra conversion.
        """
        slug = _to_hostname(v.strip())
        if not slug:
            raise ValueError("Name must contain at least one letter or digit")
        return slug


class ProjectUpdate(BaseModel):
    name: str | None = None
    description: str | None = None
    devices: list[str] | None = None


class NodeUpsert(BaseModel):
    role: str = "node"      # coordinator | sensor | actuator | gateway | observer | hub-agent | relay | node
    label: str | None = None
    node_index: int = 0


class TopologyPatch(BaseModel):
    topology: str = "standalone"   # standalone | star | mesh | hub-spoke | pipeline | custom
    app_type: str = "firmware"     # firmware | hub | hybrid


class ProjectThemePatch(BaseModel):
    theme_overrides: dict = {}   # CSS custom property name → value


class ProjectImport(BaseModel):
    source_path: str
    name: str
    description: str | None = None


# ── Firmware template written into each new project ──────────────────────────

_PLATFORMIO_TEMPLATE = """\
; {name} — ESPAI Project Firmware
; Set WIFI credentials via environment variables before building:
;   $env:ESPAI_WIFI_SSID = "MyNetwork"
;   $env:ESPAI_WIFI_PASS = "mypassword"

[platformio]
default_envs = esp32dev

[env]
framework    = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.0
build_flags =
  -D FW_VERSION=\"0.1.0\"
  -D NODE_NAME=\"{node_name}\"
  -D WIFI_SSID=\"${{sysenv.ESPAI_WIFI_SSID}}\"
  -D WIFI_PASS=\"${{sysenv.ESPAI_WIFI_PASS}}\"

[env:seeed_xiao_esp32s3]
platform = espressif32
board    = seeed_xiao_esp32s3
build_flags = ${{env.build_flags}} -D BOARD_ID=\"seeed_xiao_esp32s3\"

[env:esp32dev]
platform = espressif32
board    = esp32dev
build_flags = ${{env.build_flags}} -D BOARD_ID=\"esp32dev\"
"""

_MAIN_CPP_TEMPLATE = """\
/**
 * {name} — ESPAI Project Firmware
 *
 * Generated by ESPAI. Modify freely.
 * The node API endpoints (manifest/status/checkin/reboot/ota) are
 * inherited from the seed firmware — add your project logic below.
 */

#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <ArduinoJson.h>

#ifndef NODE_NAME
#define NODE_NAME "{node_name}"
#endif
#ifndef FW_VERSION
#define FW_VERSION "0.1.0"
#endif
#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif
#ifndef WIFI_PASS
#define WIFI_PASS ""
#endif
#ifndef BOARD_ID
#define BOARD_ID "esp32dev"
#endif

static const uint32_t WIFI_TIMEOUT_MS = 15000;

WebServer server(80);

// ── Node ID (hashed MAC) ──────────────────────────────────────────────────
#include <mbedtls/md.h>
String deriveNodeId() {{
  uint8_t mac[6], hash[32];
  WiFi.macAddress(mac);
  mbedtls_md_context_t ctx;
  mbedtls_md_init(&ctx);
  mbedtls_md_setup(&ctx, mbedtls_md_info_from_type(MBEDTLS_MD_SHA256), 0);
  mbedtls_md_starts(&ctx);
  mbedtls_md_update(&ctx, mac, 6);
  mbedtls_md_finish(&ctx, hash);
  mbedtls_md_free(&ctx);
  String id = "node-";
  for (int i = 0; i < 6; i++) {{ if (hash[i] < 0x10) id += "0"; id += String(hash[i], HEX); }}
  return id;
}}

String nodeId;

void sendJson(int code, JsonDocument& doc) {{
  String body; serializeJson(doc, body);
  server.send(code, "application/json", body);
}}

void handleManifest() {{
  JsonDocument doc;
  doc["schema"] = "ESPAI.device.v1";
  doc["id"]     = nodeId;
  doc["name"]   = NODE_NAME;
  doc["board"]  = BOARD_ID;
  doc["fw_version"] = FW_VERSION;
  JsonObject caps = doc["capabilities"].to<JsonObject>();
  caps["ota"] = true;
  sendJson(200, doc);
}}

void handleStatus() {{
  JsonDocument doc;
  doc["id"]       = nodeId;
  doc["uptime_s"] = millis() / 1000;
  doc["heap_free"]= ESP.getFreeHeap();
  doc["ip"]       = WiFi.localIP().toString();
  sendJson(200, doc);
}}

// ── TODO: add your project endpoints here ─────────────────────────────────
// void handleSensorRead() {{ ... }}

void setup() {{
  Serial.begin(115200);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  uint32_t t = millis();
  while (WiFi.status() != WL_CONNECTED && millis()-t < WIFI_TIMEOUT_MS) delay(200);

  WiFi.mode(WIFI_STA);
  nodeId = deriveNodeId();
  Serial.printf("Node ID: %s  IP: %s\\n", nodeId.c_str(), WiFi.localIP().toString().c_str());

  MDNS.begin(nodeId.c_str());
  MDNS.addService("_ESPAI-node", "_tcp", 80);

  server.on("/api/manifest", HTTP_GET,  handleManifest);
  server.on("/api/status",   HTTP_GET,  handleStatus);
  server.on("/api/reboot",   HTTP_POST, [](){{ JsonDocument d; d["status"]="rebooting"; String b; serializeJson(d,b); server.send(200,"application/json",b); delay(200); ESP.restart(); }});
  // TODO: register your project endpoints
  // server.on("/api/sensor", HTTP_GET, handleSensorRead);
  server.begin();
}}

void loop() {{
  server.handleClient();
  delay(1);
}}
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_slug(name: str) -> str:
    """Kept for backward compatibility — delegates to the canonical _to_hostname."""
    return _to_hostname(name)


def _generate_espai_md(project_id: str, name: str, description: str | None) -> str:
    """Return the content of the per-project ESPAI.md context file."""
    node_name = _to_hostname(name)
    desc_line = description.strip() if description else "New ESPAI project."
    return f"""\
# {name} — ESPAI Project Context

> Auto-generated by ESPAI. Keep this file up to date as the project evolves.
> Agents receive this file automatically before every task prompt.

**Project ID:** `{project_id}`
**Hostname slug:** `{node_name}`
**Description:** {desc_line}

---

## Hub Integration

The ESPAI hub runs at `http://espai.local:7888/` (or `http://localhost:7888/`).

### Push sensor readings from firmware

```cpp
#include <HTTPClient.h>

void pushToHub(float value) {{
  if (WiFi.status() != WL_CONNECTED) return;
  HTTPClient http;
  http.begin("http://espai.local:7888/api/projects/{project_id}/data");
  http.addHeader("Content-Type", "application/json");
  http.addHeader("X-Device-ID", nodeId);
  http.POST("{{\"value\":" + String(value, 2) + "}}");
  http.end();
}}
```

Set `HUB_PROJECT_ID` as a build flag in `platformio.ini`:
```ini
build_flags = -D HUB_PROJECT_ID=\"{project_id}\"
```

### Read cached data from hub web app

```javascript
// Works from /app/{node_name}/ (hub) or direct device access — device can be asleep
const HUB = location.pathname.startsWith("/app/");
const HUB_API = HUB ? "" : "http://espai.local:7888";
const {{ devices }} = await fetch(HUB_API + "/api/projects/{project_id}/data/latest")
  .then(r => r.json());
// devices[0].payload → the latest reading object
```

---

## Project Structure

```
projects/{project_id}/
  firmware/              ESP32 firmware — edit freely, built with PlatformIO
    platformio.ini       Board config; set WiFi credentials via env vars
    src/main.cpp         Entry point — add project logic below the TODO comment
  web/                   Hub-hosted web app — served at /app/{node_name}/
  files/                 General project files
  captures/              Device captures (private — gitignored)
  notes.md               Project notes
  ESPAI.md               This file — project context for agents
```

---

## Firmware Quickstart

```bash
cd projects/{project_id}/firmware
pio run                  # compile only
pio run -t upload        # compile + flash via USB
pio device monitor       # open serial monitor (Ctrl+C to exit)
```

Build flags are in `platformio.ini`. WiFi credentials are injected via:
```powershell
$env:ESPAI_WIFI_SSID = "MyNetwork"
$env:ESPAI_WIFI_PASS = "mypassword"
pio run
```

---

## Key Constraints for This Project

- **Never hardcode WiFi credentials** — use `${{sysenv.ESPAI_WIFI_SSID}}` in platformio.ini
- **Never modify** `firmware/seed/` or `firmware/provision/` — they are platform templates
- **Run `pio run` and fix all errors** before committing any firmware change
- **Hub checkins are fire-and-forget** — never block the firmware loop on hub availability
- **AP fallback is required** — if WiFi fails, start `ESPAI-{{node_id_suffix}}` hotspot
- **Every hub web UI element** needs `data-tip="…"` (see CLAUDE.md)

---

## Platform Reference

- Full design spec: `docs/DESIGN_SPEC.md`
- Agent rules:      `agents/rules.md`
- Hub API docs:     `http://espai.local:7888/docs`
- Seed firmware:    `firmware/seed/src/main.cpp` (read-only reference)
"""


def _create_project_folder(project_id: str, name: str, description: str | None) -> None:
    node_name = _to_hostname(name)
    proj_dir  = PROJECTS_DIR / project_id
    fw_dir    = proj_dir / "firmware" / "src"
    fw_dir.mkdir(parents=True, exist_ok=True)
    (proj_dir / "workers").mkdir(exist_ok=True)
    (proj_dir / "captures").mkdir(exist_ok=True)

    # Project metadata
    meta = {
        "schema": "ESPAI.project.v1",
        "id": project_id,
        "name": name,
        "description": description or "",
        "created": _now(),
    }
    (proj_dir / ".ESPAI-project.json").write_text(
        json.dumps(meta, indent=2), encoding="utf-8"
    )

    # Human notes
    (proj_dir / "notes.md").write_text(
        f"# {name}\n\n{description or 'New ESPAI project.'}\n\n## Devices\n\n## Notes\n",
        encoding="utf-8",
    )

    # Firmware scaffold
    (fw_dir.parent / "platformio.ini").write_text(
        _PLATFORMIO_TEMPLATE.format(name=name, node_name=node_name),
        encoding="utf-8",
    )
    (fw_dir / "main.cpp").write_text(
        _MAIN_CPP_TEMPLATE.format(name=name, node_name=node_name),
        encoding="utf-8",
    )

    # Gitignore for project dir (captures are private)
    (proj_dir / ".gitignore").write_text(
        "captures/\n.pio/\n*.private.*\nsecrets.*\n", encoding="utf-8"
    )

    # Per-project context file — read by agents before every task
    (proj_dir / "ESPAI.md").write_text(
        _generate_espai_md(project_id, name, description), encoding="utf-8"
    )

    # Initialize git repo for version history (silent if git unavailable)
    git_helper.git_init(proj_dir, f"init: {name} project scaffold")


_NODE_ROLES = {"coordinator","sensor","actuator","gateway","observer","hub-agent","relay","node"}
_TOPOLOGIES = {"standalone","star","mesh","hub-spoke","pipeline","custom"}
_APP_TYPES  = {"firmware","hub","hybrid"}


def _get_nodes(conn, project_id: str) -> list[dict]:
    rows = conn.execute(
        "SELECT device_id, role, label, node_index FROM project_nodes WHERE project_id=? ORDER BY node_index",
        (project_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def _sync_devices_col(conn, project_id: str) -> None:
    """Keep projects.devices JSON in sync with project_nodes (backward compat)."""
    rows = conn.execute(
        "SELECT device_id FROM project_nodes WHERE project_id=? ORDER BY node_index",
        (project_id,),
    ).fetchall()
    ids = json.dumps([r["device_id"] for r in rows])
    conn.execute("UPDATE projects SET devices=? WHERE id=?", (ids, project_id))


def _row_to_dict(row, conn=None) -> dict:
    d = dict(row)
    if d.get("devices"):
        try:
            d["devices"] = json.loads(d["devices"])
        except Exception:
            d["devices"] = []
    else:
        d["devices"] = []
    if d.get("meta"):
        try:
            d["meta"] = json.loads(d["meta"])
        except Exception:
            pass
    # Attach structured nodes list
    if conn is not None:
        d["nodes"] = _get_nodes(conn, d["id"])
    return d


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/")
def list_projects():
    with get_conn() as conn:
        rows = conn.execute("SELECT * FROM projects ORDER BY created DESC").fetchall()
        return [_row_to_dict(r, conn) for r in rows]


@router.get("/{project_id}")
def get_project(project_id: str):
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
        if not row:
            raise HTTPException(404, f"Project {project_id!r} not found")
        return _row_to_dict(row, conn)


@router.get("/{project_id}/app-url")
def project_app_url(project_id: str, request: Request):
    """
    Return the best URL to open the project's web interface.
    Priority: hub-hosted web app > linked device IP > mDNS slug.
    """
    proj_dir = PROJECTS_DIR / project_id
    if not proj_dir.exists():
        raise HTTPException(404, f"Project {project_id!r} not found")

    # Hub-hosted web app? Use slug URL for Caddy-friendliness.
    if (proj_dir / "web" / "index.html").exists():
        base = str(request.base_url).rstrip("/")
        with get_conn() as conn:
            name = conn.execute("SELECT name FROM projects WHERE id=?", (project_id,)).fetchone()
        slug = _safe_slug(name["name"]) if name else project_id
        return {"url": f"{base}/app/{slug}/", "host": "hub", "slug": slug, "project_id": project_id}

    # Linked device IP?
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
    if row:
        dev_ids = json.loads(row["devices"] or "[]")
        for did in dev_ids:
            with get_conn() as conn:
                dev = conn.execute("SELECT ip FROM devices WHERE id=?", (did,)).fetchone()
            if dev and dev["ip"]:
                return {"url": f"http://{dev['ip']}/", "host": "device"}

    # mDNS slug from project name
    with get_conn() as conn:
        row = conn.execute("SELECT name FROM projects WHERE id=?", (project_id,)).fetchone()
    if row:
        slug = _safe_slug(row["name"])
        return {"url": f"http://{slug}.local/", "host": "mdns"}

    return {"url": None, "host": None}


@router.get("/{project_id}/files")
def project_files(project_id: str):
    """List files in the project directory on disk."""
    proj_dir = PROJECTS_DIR / project_id
    if not proj_dir.exists():
        return {"project_id": project_id, "files": []}
    files = []
    for f in sorted(proj_dir.rglob("*")):
        if f.is_file() and ".pio" not in str(f):
            rel = f.relative_to(proj_dir).as_posix()
            files.append({"path": rel, "size_bytes": f.stat().st_size})
    return {"project_id": project_id, "root": str(proj_dir), "files": files}


# ── In-hub file editor ────────────────────────────────────────────────────────

_FILE_EDITOR_MAX_BYTES = 512 * 1024   # 512 KB — larger files won't fit comfortably in editor
_FILE_WRITE_MAX_BYTES  = 1 * 1024 * 1024  # 1 MB write limit
_BLOCKED_FILE_PATTERNS = (".env", "secrets", ".private", "local.yaml", "secrets.yaml")


class FileWrite(BaseModel):
    content: str


def _resolve_project_file(project_id: str, file_path: str) -> tuple[Path, Path]:
    """
    Resolve a project-relative file_path to an absolute Path.
    Returns (proj_dir, target). Raises 403 on path traversal, 400 on blocked names.
    """
    proj_dir = (PROJECTS_DIR / project_id).resolve()
    target   = (proj_dir / file_path).resolve()
    try:
        target.relative_to(proj_dir)
    except ValueError:
        raise HTTPException(403, "Path traversal not allowed")
    # Block access to private/secret files
    lower = file_path.lower()
    if any(pat in lower for pat in _BLOCKED_FILE_PATTERNS):
        raise HTTPException(403, f"Access to {file_path!r} is blocked")
    return proj_dir, target


@router.get("/{project_id}/files/{file_path:path}")
def read_project_file(project_id: str, file_path: str):
    """Read a text file from the project directory for in-hub editing."""
    proj_dir, target = _resolve_project_file(project_id, file_path)
    if not target.exists():
        raise HTTPException(404, "File not found")
    if not target.is_file():
        raise HTTPException(400, "Not a file")
    size = target.stat().st_size
    if size > _FILE_EDITOR_MAX_BYTES:
        raise HTTPException(413, f"File is {size // 1024} KB — too large for in-hub editor (max 512 KB)")
    content = target.read_text(encoding="utf-8", errors="replace")
    return {"path": file_path, "content": content, "size_bytes": size}


@router.put("/{project_id}/files/{file_path:path}")
def write_project_file(project_id: str, file_path: str, body: FileWrite):
    """Save edited content back to a file in the project directory."""
    proj_dir, target = _resolve_project_file(project_id, file_path)
    encoded = body.content.encode("utf-8")
    if len(encoded) > _FILE_WRITE_MAX_BYTES:
        raise HTTPException(413, "Content exceeds 1 MB write limit")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body.content, encoding="utf-8")
    # Auto-commit to project git history (silent if not a repo)
    git_helper.git_commit(proj_dir, f"edit: {file_path}", [file_path])
    return {"path": file_path, "size_bytes": len(encoded), "saved": True}


@router.post("/{project_id}/files/{file_path:path}")
def create_project_file(project_id: str, file_path: str, body: FileWrite):
    """Create a new file in the project directory."""
    proj_dir, target = _resolve_project_file(project_id, file_path)
    if target.exists():
        raise HTTPException(409, f"{file_path!r} already exists — use PUT to overwrite")
    encoded = body.content.encode("utf-8")
    if len(encoded) > _FILE_WRITE_MAX_BYTES:
        raise HTTPException(413, "Content exceeds 1 MB write limit")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body.content, encoding="utf-8")
    return {"path": file_path, "size_bytes": len(encoded), "created": True}


@router.delete("/{project_id}/files/{file_path:path}")
def delete_project_file(project_id: str, file_path: str):
    """Delete a file from the project directory."""
    proj_dir, target = _resolve_project_file(project_id, file_path)
    # Protect critical project files
    protected = {".ESPAI-project.json", "ESPAI.md", "platformio.ini"}
    if target.name in protected:
        raise HTTPException(403, f"{target.name} is protected and cannot be deleted from the editor")
    if not target.exists():
        raise HTTPException(404, "File not found")
    target.unlink()
    return {"path": file_path, "deleted": True}


_IMPORT_IGNORE = shutil.ignore_patterns(".pio", ".git", "__pycache__", "*.pyc", "node_modules")

_IMPORT_SIZE_LIMIT = 200 * 1024 * 1024  # 200 MB safety cap


def _dir_size(path: Path) -> int:
    return sum(f.stat().st_size for f in path.rglob("*") if f.is_file())


@router.post("/import")
def import_project(data: ProjectImport):
    src = Path(data.source_path)
    if not src.exists():
        raise HTTPException(400, f"Path not found: {data.source_path!r}")
    if not src.is_dir():
        raise HTTPException(400, "source_path must be a directory")

    # Size guard (skip .pio which can be huge)
    copyable = [
        f for f in src.rglob("*")
        if f.is_file() and ".pio" not in f.parts and ".git" not in f.parts
    ]
    total_bytes = sum(f.stat().st_size for f in copyable)
    if total_bytes > _IMPORT_SIZE_LIMIT:
        raise HTTPException(
            400,
            f"Project is {total_bytes // 1_048_576} MB — exceeds 200 MB import limit. "
            "Run `pio run --target clean` first to remove build artifacts.",
        )

    has_pio = (src / "platformio.ini").exists()
    project_id = secrets.token_hex(6)
    now = _now()

    with get_conn() as conn:
        conn.execute(
            "INSERT INTO projects (id, name, description, devices, created) VALUES (?,?,?,?,?)",
            (project_id, data.name, data.description, json.dumps([]), now),
        )

    proj_dir = PROJECTS_DIR / project_id
    fw_dest  = proj_dir / "firmware"
    try:
        shutil.copytree(str(src), str(fw_dest), ignore=_IMPORT_IGNORE)
    except Exception as exc:
        shutil.rmtree(str(proj_dir), ignore_errors=True)
        with get_conn() as conn:
            conn.execute("DELETE FROM projects WHERE id=?", (project_id,))
        raise HTTPException(500, f"Copy failed: {exc}")

    (proj_dir / "workers").mkdir(exist_ok=True)
    (proj_dir / "captures").mkdir(exist_ok=True)

    meta = {
        "schema": "ESPAI.project.v1",
        "id": project_id,
        "name": data.name,
        "description": data.description or "",
        "created": now,
        "imported_from": str(src),
    }
    (proj_dir / ".ESPAI-project.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    notes = (
        f"# {data.name}\n\n{data.description or 'Imported project.'}\n\n"
        f"Imported from: `{src}`\n\n"
        + ("PlatformIO project detected — build with `pio run`.\n" if has_pio else "")
        + "\n## Notes\n"
    )
    (proj_dir / "notes.md").write_text(notes, encoding="utf-8")
    (proj_dir / ".gitignore").write_text("captures/\n.pio/\n*.private.*\nsecrets.*\n", encoding="utf-8")

    file_count = len(copyable)
    return {
        "id": project_id,
        "name": data.name,
        "created": now,
        "source_path": str(src),
        "file_count": file_count,
        "has_platformio": has_pio,
    }


def _ini_version(ini_path: Path) -> str:
    """Extract FW_VERSION from platformio.ini build_flags, or return '0.0.0'."""
    try:
        text = ini_path.read_text(encoding="utf-8")
        for line in text.splitlines():
            m = re.search(r'FW_VERSION\\?"([^"\\]+)\\?"', line)
            if m:
                return m.group(1)
    except Exception:
        pass
    return "0.0.0"


@router.post("/{project_id}/import-build")
def import_build(project_id: str, channel: str = "dev"):
    """
    Find the most recently compiled firmware.bin in the project's .pio/build/
    directory and register it in the OTA catalog — no file upload required.
    Run 'pio run' first to produce the binary.
    """
    proj_dir = PROJECTS_DIR / project_id
    if not proj_dir.exists():
        raise HTTPException(404, f"Project {project_id!r} not found")

    build_root = proj_dir / "firmware" / ".pio" / "build"
    if not build_root.exists():
        raise HTTPException(
            404,
            "No .pio/build directory found — run 'pio run' in the firmware folder first.",
        )

    bins = [f for f in build_root.glob("**/firmware.bin") if f.is_file()]
    if not bins:
        raise HTTPException(
            404,
            "No firmware.bin found in .pio/build — run 'pio run' first.",
        )

    # Pick the freshest binary (most recent build wins)
    latest = max(bins, key=lambda f: f.stat().st_mtime)
    board   = latest.parent.name   # env directory name = board/env identifier
    version = _ini_version(proj_dir / "firmware" / "platformio.ini")

    content = latest.read_bytes()
    if not content:
        raise HTTPException(400, "firmware.bin is empty — the build may have failed.")

    sha256 = hashlib.sha256(content).hexdigest()

    FIRMWARE_CATALOG_DIR.mkdir(parents=True, exist_ok=True)
    entry_dir = FIRMWARE_CATALOG_DIR / f"{board}-{version}"
    entry_dir.mkdir(parents=True, exist_ok=True)
    (entry_dir / "firmware.bin").write_bytes(content)

    # Use the project name as the human-readable firmware label
    with get_conn() as conn:
        proj_row = conn.execute("SELECT name FROM projects WHERE id=?", (project_id,)).fetchone()
    proj_name = proj_row["name"] if proj_row else project_id
    label = f"{proj_name} v{version}"

    meta = {
        "schema":     "ESPAI.firmware.v1",
        "board":      board,
        "version":    version,
        "channel":    channel,
        "label":      label,
        "project_id": project_id,
        "filename":   "firmware.bin",
        "size_bytes": len(content),
        "sha256":     sha256,
        "uploaded":   _now(),
        "known_good": False,
        "source_bin": str(latest),
    }
    (entry_dir / "firmware.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return meta


@router.post("/")
def create_project(data: ProjectCreate):
    # name is already coerced to hostname-safe form by the validator
    project_id = secrets.token_hex(6)
    slug = data.name   # validator already ran _to_hostname
    now = _now()
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO projects (id, name, description, devices, slug, created) VALUES (?,?,?,?,?,?)",
            (project_id, data.name, data.description, json.dumps(data.devices), slug, now),
        )
    _create_project_folder(project_id, data.name, data.description)
    _mdns.register_project(slug, project_id)
    return {"id": project_id, "name": data.name, "slug": slug, "created": now}


@router.patch("/{project_id}/rename")
def rename_project(project_id: str, data: ProjectCreate):
    """Rename a project, automatically updating the slug/hostname."""
    with get_conn() as conn:
        row = conn.execute("SELECT id, slug, name FROM projects WHERE id=?", (project_id,)).fetchone()
        if not row:
            raise HTTPException(404, f"Project {project_id!r} not found")
        old_slug = row["slug"] or _to_hostname(row["name"])
        new_slug = _to_hostname(data.name)
        conn.execute(
            "UPDATE projects SET name=?, slug=?, updated=? WHERE id=?",
            (data.name, new_slug, _now(), project_id),
        )
    if old_slug != new_slug:
        _mdns.unregister_project(old_slug)
    _mdns.register_project(new_slug, project_id)
    return {"id": project_id, "name": data.name, "slug": new_slug}


@router.patch("/{project_id}")
def update_project(project_id: str, data: ProjectUpdate):
    updates, vals = [], []
    if data.name is not None:
        updates.append("name=?"); vals.append(data.name)
    if data.description is not None:
        updates.append("description=?"); vals.append(data.description)
    if data.devices is not None:
        # Sync both the legacy JSON column AND project_nodes table
        updates.append("devices=?"); vals.append(json.dumps(data.devices))
        if updates:
            vals.append(project_id)
            with get_conn() as conn:
                if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
                    raise HTTPException(404, f"Project {project_id!r} not found")
                conn.execute(f"UPDATE projects SET {', '.join(updates)} WHERE id=?", vals)
                # Sync nodes table: remove stale entries, add new ones with default role
                existing = {r["device_id"] for r in conn.execute(
                    "SELECT device_id FROM project_nodes WHERE project_id=?", (project_id,)
                ).fetchall()}
                new_set = set(data.devices)
                for did in existing - new_set:
                    conn.execute("DELETE FROM project_nodes WHERE project_id=? AND device_id=?", (project_id, did))
                for idx, did in enumerate(data.devices):
                    if did not in existing:
                        conn.execute(
                            "INSERT OR IGNORE INTO project_nodes (project_id, device_id, role, node_index) VALUES (?,?,?,?)",
                            (project_id, did, "node", idx),
                        )
            return {"status": "updated"}
    if not updates:
        return {"status": "no-op"}
    vals.append(project_id)
    with get_conn() as conn:
        if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
            raise HTTPException(404, f"Project {project_id!r} not found")
        conn.execute(f"UPDATE projects SET {', '.join(updates)} WHERE id=?", vals)
    return {"status": "updated"}


# ── Project node management ───────────────────────────────────────────────────

@router.get("/{project_id}/nodes")
def list_project_nodes(project_id: str):
    with get_conn() as conn:
        if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
            raise HTTPException(404, f"Project {project_id!r} not found")
        return _get_nodes(conn, project_id)


@router.put("/{project_id}/nodes/{device_id}")
def upsert_project_node(project_id: str, device_id: str, body: NodeUpsert):
    if body.role not in _NODE_ROLES:
        raise HTTPException(400, f"role must be one of: {', '.join(sorted(_NODE_ROLES))}")
    with get_conn() as conn:
        if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
            raise HTTPException(404, f"Project {project_id!r} not found")
        conn.execute(
            """INSERT INTO project_nodes (project_id, device_id, role, label, node_index)
               VALUES (?,?,?,?,?)
               ON CONFLICT(project_id, device_id) DO UPDATE SET
                 role=excluded.role, label=excluded.label, node_index=excluded.node_index""",
            (project_id, device_id, body.role, body.label, body.node_index),
        )
        _sync_devices_col(conn, project_id)
    return {"project_id": project_id, "device_id": device_id, "role": body.role}


@router.delete("/{project_id}/nodes/{device_id}")
def remove_project_node(project_id: str, device_id: str):
    with get_conn() as conn:
        conn.execute(
            "DELETE FROM project_nodes WHERE project_id=? AND device_id=?",
            (project_id, device_id),
        )
        _sync_devices_col(conn, project_id)
    return {"project_id": project_id, "device_id": device_id, "removed": True}


@router.get("/{project_id}/topology")
def get_project_topology(project_id: str):
    meta = _read_project_meta(project_id)
    return {
        "topology": meta.get("topology", "standalone"),
        "app_type": meta.get("app_type", "firmware"),
    }


@router.put("/{project_id}/topology")
def set_project_topology(project_id: str, body: TopologyPatch):
    if body.topology not in _TOPOLOGIES:
        raise HTTPException(400, f"topology must be one of: {', '.join(sorted(_TOPOLOGIES))}")
    if body.app_type not in _APP_TYPES:
        raise HTTPException(400, f"app_type must be one of: {', '.join(sorted(_APP_TYPES))}")
    with get_conn() as conn:
        if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
            raise HTTPException(404, f"Project {project_id!r} not found")
    meta = _read_project_meta(project_id)
    meta["topology"] = body.topology
    meta["app_type"] = body.app_type
    _write_project_meta(project_id, meta)
    return {"project_id": project_id, "topology": body.topology, "app_type": body.app_type}


@router.delete("/{project_id}")
def delete_project(project_id: str):
    with get_conn() as conn:
        row = conn.execute("SELECT slug, name FROM projects WHERE id=?", (project_id,)).fetchone()
        conn.execute("DELETE FROM projects WHERE id=?", (project_id,))
    if row:
        _mdns.unregister_project(row["slug"] or _to_hostname(row["name"]))
    return {"status": "deleted"}


_APPROVAL_MODES = ("prototype", "dev", "stable")


@router.get("/{project_id}/approval-mode")
def get_approval_mode(project_id: str):
    """
    Return the agent approval mode for this project.
    prototype — changes ship fast; review panel is minimal; no notes required
    dev       — default; review required; full diff + notes available
    stable    — review required; diff must be acknowledged before approve
    """
    meta = _read_project_meta(project_id)
    return {"mode": meta.get("agent_approval_mode", "dev")}


@router.put("/{project_id}/approval-mode")
def set_approval_mode(project_id: str, mode: str):
    """Set the agent approval mode for this project."""
    if mode not in _APPROVAL_MODES:
        raise HTTPException(400, f"mode must be one of: {', '.join(_APPROVAL_MODES)}")
    with get_conn() as conn:
        exists = conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone()
    if not exists:
        raise HTTPException(404, f"Project {project_id!r} not found")
    meta = _read_project_meta(project_id)
    meta["agent_approval_mode"] = mode
    _write_project_meta(project_id, meta)
    return {"mode": mode}


@router.get("/{project_id}/git/log")
def project_git_log(project_id: str, limit: int = 40):
    """Return the git commit history for this project's directory."""
    proj_dir = PROJECTS_DIR / project_id
    commits = git_helper.git_log(proj_dir, limit=min(limit, 200))
    return {"project_id": project_id, "commits": commits, "is_repo": git_helper.is_repo(proj_dir)}


@router.post("/{project_id}/regenerate-context")
def regenerate_project_context(project_id: str):
    """Regenerate the per-project ESPAI.md context file from current project metadata."""
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
    if not row:
        raise HTTPException(404, f"Project {project_id!r} not found")
    proj_dir = PROJECTS_DIR / project_id
    proj_dir.mkdir(parents=True, exist_ok=True)
    content = _generate_espai_md(project_id, row["name"], row["description"])
    (proj_dir / "ESPAI.md").write_text(content, encoding="utf-8")
    return {"status": "ok", "path": str(proj_dir / "ESPAI.md")}


# ── Project theme overrides ───────────────────────────────────────────────────

def _project_meta_path(project_id: str) -> Path:
    return PROJECTS_DIR / project_id / ".ESPAI-project.json"


def _read_project_meta(project_id: str) -> dict:
    p = _project_meta_path(project_id)
    if p.exists():
        try:
            return json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def _write_project_meta(project_id: str, meta: dict) -> None:
    p = _project_meta_path(project_id)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(meta, indent=2), encoding="utf-8")


@router.get("/{project_id}/theme")
def get_project_theme(project_id: str):
    """
    Return the merged theme token set for this project.

    Hub-level tokens are loaded from the active theme, then project-level
    overrides (stored in .ESPAI-project.json) are applied on top.
    The result is a flat dict of CSS custom property name → value.
    """
    # Load hub active theme tokens
    try:
        import yaml
        theme_path = DESIGN_DIR / "themes" / ACTIVE_THEME / "theme.yaml"
        hub_tokens: dict = {}
        if theme_path.exists():
            raw = yaml.safe_load(theme_path.read_text(encoding="utf-8")) or {}
            hub_tokens = raw.get("tokens", {})
    except Exception:
        hub_tokens = {}

    # Apply project overrides
    meta           = _read_project_meta(project_id)
    project_tokens = meta.get("theme_overrides", {})

    merged = {**hub_tokens, **project_tokens}
    return {
        "project_id":      project_id,
        "active_theme":    ACTIVE_THEME,
        "tokens":          merged,
        "project_overrides": project_tokens,
    }


@router.put("/{project_id}/theme")
def set_project_theme(project_id: str, data: ProjectThemePatch):
    """
    Save project-level theme override tokens to .ESPAI-project.json.
    Pass an empty dict to clear all overrides.
    """
    with get_conn() as conn:
        if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
            raise HTTPException(404, f"Project {project_id!r} not found")
    meta = _read_project_meta(project_id)
    meta["theme_overrides"] = data.theme_overrides
    _write_project_meta(project_id, meta)
    return {"status": "saved", "project_id": project_id, "theme_overrides": data.theme_overrides}


@router.post("/{project_id}/apply-hub-theme")
def apply_hub_theme_to_project(project_id: str):
    """
    Generate a hub-theme.css file in projects/{id}/web/ containing the active
    hub theme tokens as CSS custom properties on :root.

    Add <link rel="stylesheet" href="/app/{slug}/hub-theme.css"> to the project's
    web/index.html to apply the hub palette to the project web app automatically.
    """
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
    if not row:
        raise HTTPException(404, f"Project {project_id!r} not found")

    # Load active hub tokens (same source as /api/design/tokens)
    from ..registry.loader import scan_folder as _scan
    from ..config import DESIGN_DIR as _DESIGN_DIR
    from .. import theme_scheduler as _ts
    from ..db import get_setting as _gs

    themes = _scan(_DESIGN_DIR / "themes", "theme")
    dynamic_theme = _ts.get_dynamic_theme()
    theme_name    = dynamic_theme or _gs("active_theme") or ACTIVE_THEME or "retro"
    match = next((t for t in themes if t.get("name") == theme_name), None)
    if not match and themes:
        match = next((t for t in themes if t.get("name") == "retro"), themes[0])
    tokens = {**(match.get("tokens", {}) if match else {}), **_ts.get_active_overrides()}

    # Build CSS file
    lines = [":root {"]
    for key, value in tokens.items():
        # Convert ESPAI token key to CSS custom property: color.accent → --color-accent
        css_var = "--" + key.replace(".", "-")
        lines.append(f"  {css_var}: {value};")
    lines.append("}")
    css = "\n".join(lines) + "\n"

    web_dir = PROJECTS_DIR / project_id / "web"
    web_dir.mkdir(parents=True, exist_ok=True)
    css_path = web_dir / "hub-theme.css"
    css_path.write_text(css, encoding="utf-8")
    git_helper.git_commit(PROJECTS_DIR / project_id, "theme: apply hub theme tokens")

    slug = row["slug"] or row["name"]
    return {
        "status": "ok",
        "path": str(css_path),
        "theme": theme_name,
        "token_count": len(tokens),
        "link_tag": f'<link rel="stylesheet" href="/app/{slug}/hub-theme.css">',
    }


# ── Project public page serving ───────────────────────────────────────────────
# Serves static files from projects/{project_id}/workers/public/
# e.g. GET /api/projects/c9ac1baa9ba4/page  → workers/public/index.html

@router.get("/{project_id}/page")
@router.get("/{project_id}/page/{file_path:path}")
def serve_project_page(project_id: str, file_path: str = "index.html"):
    """Serve static files from a project's workers/public/ directory."""
    pub_dir = (PROJECTS_DIR / project_id / "workers" / "public").resolve()
    if not pub_dir.exists():
        raise HTTPException(404, "No public page found for this project")

    target = (pub_dir / file_path).resolve()
    # Guard against path traversal
    if not str(target).startswith(str(pub_dir)):
        raise HTTPException(403, "Path traversal not allowed")
    if not target.exists() or not target.is_file():
        # SPA fallback
        target = pub_dir / "index.html"
    if not target.exists():
        raise HTTPException(404, f"File not found: {file_path}")

    media_type, _ = mimetypes.guess_type(str(target))
    return FileResponse(str(target), media_type=media_type or "application/octet-stream")


# ── ZIP import ────────────────────────────────────────────────────────────────

_ZIP_MAX_BYTES = 100 * 1024 * 1024          # 100 MB hard limit
_ZIP_SKIP_PREFIXES = {                       # build artifacts / caches to drop
    ".pio/", "__pycache__/", ".git/",
    "node_modules/", ".venv/", "venv/",
    "build/", "dist/",
}
_PORT_CRITERIA = [
    "All source files in source/ have been read and a porting plan summarised in notes.md",
    "Hub workers created for any processing that moved off the ESP32",
    "Dashboard cards created for sensor data the firmware previously served locally",
    "Firmware updated to use ESPAI hub checkin pattern (fire-and-forget HTTP POST)",
    "Firmware falls back to AP mode and local operation when hub is unreachable",
    "No hardcoded credentials, IPs, or MAC addresses remain in source",
    "pio run passes with no errors in projects/{id}/firmware/",
]


@router.post("/import-zip")
async def import_project_from_zip(
    file: UploadFile = File(...),
    name: str = Form(""),
    description: str = Form(""),
):
    """
    Create a new ESPAI project from an uploaded ZIP file.

    Accepts PlatformIO, Arduino IDE, or any ESP32 project zip.  Extracts the
    source to projects/{id}/source/, scaffolds the full ESPAI project structure
    alongside it, and auto-creates a draft 'port-to-hub' Agent Bench task so
    Claude can analyse and port the project on demand.
    """
    if not (file.filename or "").lower().endswith(".zip"):
        raise HTTPException(400, "Only .zip files are accepted")

    content = await file.read(_ZIP_MAX_BYTES + 1)
    if len(content) > _ZIP_MAX_BYTES:
        raise HTTPException(413, "ZIP must be under 100 MB")

    try:
        zf = zipfile.ZipFile(io.BytesIO(content))
    except zipfile.BadZipFile:
        raise HTTPException(400, "File is not a valid ZIP archive")

    # Derive project name from zip filename when not supplied
    zip_stem = Path(file.filename or "imported").stem
    project_name = name.strip() or zip_stem or "Imported Project"
    desc = description.strip() or None

    # Create project in DB and scaffold directories
    project_id = secrets.token_hex(6)
    slug = _to_hostname(project_name)
    now = _now()
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO projects (id, name, description, devices, slug, created) VALUES (?,?,?,?,?,?)",
            (project_id, project_name, desc or "", json.dumps([]), slug, now),
        )
    _create_project_folder(project_id, project_name, desc)

    # Extract ZIP → projects/{id}/source/
    proj_dir  = PROJECTS_DIR / project_id
    source_dir = proj_dir / "source"
    source_dir.mkdir(exist_ok=True)

    # Persist the original ZIP for reference
    (proj_dir / "source.zip").write_bytes(content)

    # Detect whether the ZIP has a single top-level folder to strip
    names = zf.namelist()
    top_prefix = ""
    if names:
        first = names[0].split("/")[0]
        if first and all(n == first or n.startswith(first + "/") for n in names):
            top_prefix = first + "/"

    file_count   = 0
    has_pio      = False
    has_arduino  = False
    source_root  = str(source_dir.resolve())

    for member in zf.infolist():
        rel = member.filename
        if top_prefix:
            rel = rel[len(top_prefix):]
        if not rel:
            continue
        # Drop build artifacts / caches
        if any(rel.startswith(p) or ("/" + p) in rel for p in _ZIP_SKIP_PREFIXES):
            continue
        # Guard against path traversal
        dest = (source_dir / rel).resolve()
        if not str(dest).startswith(source_root):
            continue
        if member.is_dir():
            dest.mkdir(parents=True, exist_ok=True)
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(zf.read(member.filename))
            file_count += 1
            if rel in ("platformio.ini",) or rel.endswith("/platformio.ini"):
                has_pio = True
            if rel.endswith(".ino"):
                has_arduino = True

    zf.close()

    project_type = "platformio" if has_pio else "arduino" if has_arduino else "unknown"

    # Register mDNS advertisement
    _mdns.register_project(slug, project_id)

    # Auto-create draft porting task (best-effort — Agent Bench may be disabled)
    task_id = None
    try:
        task_id = str(uuid.uuid4())
        allowed = [f"projects/{project_id}/", "workers/", "recipes/", "cards/"]
        task_desc = (
            f"Imported from **{file.filename}** — detected as: **{project_type}**.\n\n"
            "## Porting instructions\n\n"
            "1. **Read** all files in `source/` — understand what the project does\n"
            "2. **Summarise** your findings in `notes.md` (sensor types, endpoints, "
            "web server routes, external services, heavy processing)\n"
            "3. **Port web server routes** → hub workers in `projects/{id}/workers/` "
            "or shared `workers/`\n"
            "4. **Port sensor dashboards** → ESPAI cards in `cards/`\n"
            "5. **Port pipelines** → ESPAI recipes in `recipes/`\n"
            "6. **Update firmware** in `projects/{id}/firmware/` to replace local "
            "web server with hub checkin calls — keep AP fallback for offline use\n"
            "7. **Run `pio run`** in `projects/{id}/firmware/` and fix all errors\n"
            "8. **Never hardcode** credentials, IPs, or MAC addresses\n"
        )
        with get_conn() as conn:
            conn.execute(
                """INSERT INTO agent_tasks
                   (id, project_id, title, description, template, status,
                    allowed_paths, acceptance_criteria, context,
                    context_type, context_id, parent_task_id,
                    lane, adapter_id, created, updated)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    task_id, project_id,
                    f"Port '{project_name}' to ESPAI",
                    task_desc,
                    "port-to-hub", "draft",
                    json.dumps(allowed),
                    json.dumps(_PORT_CRITERIA),
                    None,
                    "project", project_id, None,
                    "dev", None,
                    now, now,
                ),
            )
    except Exception:
        task_id = None  # agent bench disabled or DB error — not fatal

    return {
        "id":            project_id,
        "name":          project_name,
        "slug":          slug,
        "created":       now,
        "file_count":    file_count,
        "has_platformio": has_pio,
        "has_arduino":   has_arduino,
        "project_type":  project_type,
        "task_id":       task_id,
    }
