import json
import re
import secrets
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from ..config import ACTIVE_THEME, DESIGN_DIR, FIRMWARE_CATALOG_DIR, PROJECTS_DIR
from ..db import get_conn

router = APIRouter()

_SAFE_NAME = re.compile(r"[^\w\s\-\.]")  # strip unsafe chars from folder names


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class ProjectCreate(BaseModel):
    name: str
    description: str | None = None
    devices: list[str] = []


class ProjectUpdate(BaseModel):
    name: str | None = None
    description: str | None = None
    devices: list[str] | None = None


class ProjectThemePatch(BaseModel):
    theme_overrides: dict = {}   # CSS custom property name → value


# ── Firmware template written into each new project ──────────────────────────

_PLATFORMIO_TEMPLATE = """\
; {name} — ESPAI Project Firmware
; Set WIFI credentials via environment variables before building:
;   $env:ESPAI_WIFI_SSID = "MyNetwork"
;   $env:ESPAI_WIFI_PASS = "mypassword"

[platformio]
default_envs = esp32dev

[env]
framework    = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.0
build_flags =
  -D FW_VERSION=\"0.1.0\"
  -D NODE_NAME=\"{node_name}\"
  -D WIFI_SSID=\"${{sysenv.ESPAI_WIFI_SSID}}\"
  -D WIFI_PASS=\"${{sysenv.ESPAI_WIFI_PASS}}\"

[env:seeed_xiao_esp32s3]
platform = espressif32
board    = seeed_xiao_esp32s3
build_flags = ${{env.build_flags}} -D BOARD_ID=\"seeed_xiao_esp32s3\"

[env:esp32dev]
platform = espressif32
board    = esp32dev
build_flags = ${{env.build_flags}} -D BOARD_ID=\"esp32dev\"
"""

_MAIN_CPP_TEMPLATE = """\
/**
 * {name} — ESPAI Project Firmware
 *
 * Generated by ESPAI. Modify freely.
 * The node API endpoints (manifest/status/checkin/reboot/ota) are
 * inherited from the seed firmware — add your project logic below.
 */

#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <ArduinoJson.h>

#ifndef NODE_NAME
#define NODE_NAME "{node_name}"
#endif
#ifndef FW_VERSION
#define FW_VERSION "0.1.0"
#endif
#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif
#ifndef WIFI_PASS
#define WIFI_PASS ""
#endif
#ifndef BOARD_ID
#define BOARD_ID "esp32dev"
#endif

static const uint32_t WIFI_TIMEOUT_MS = 15000;

WebServer server(80);

// ── Node ID (hashed MAC) ──────────────────────────────────────────────────
#include <mbedtls/md.h>
String deriveNodeId() {{
  uint8_t mac[6], hash[32];
  WiFi.macAddress(mac);
  mbedtls_md_context_t ctx;
  mbedtls_md_init(&ctx);
  mbedtls_md_setup(&ctx, mbedtls_md_info_from_type(MBEDTLS_MD_SHA256), 0);
  mbedtls_md_starts(&ctx);
  mbedtls_md_update(&ctx, mac, 6);
  mbedtls_md_finish(&ctx, hash);
  mbedtls_md_free(&ctx);
  String id = "node-";
  for (int i = 0; i < 6; i++) {{ if (hash[i] < 0x10) id += "0"; id += String(hash[i], HEX); }}
  return id;
}}

String nodeId;

void sendJson(int code, JsonDocument& doc) {{
  String body; serializeJson(doc, body);
  server.send(code, "application/json", body);
}}

void handleManifest() {{
  JsonDocument doc;
  doc["schema"] = "ESPAI.device.v1";
  doc["id"]     = nodeId;
  doc["name"]   = NODE_NAME;
  doc["board"]  = BOARD_ID;
  doc["fw_version"] = FW_VERSION;
  JsonObject caps = doc["capabilities"].to<JsonObject>();
  caps["ota"] = true;
  sendJson(200, doc);
}}

void handleStatus() {{
  JsonDocument doc;
  doc["id"]       = nodeId;
  doc["uptime_s"] = millis() / 1000;
  doc["heap_free"]= ESP.getFreeHeap();
  doc["ip"]       = WiFi.localIP().toString();
  sendJson(200, doc);
}}

// ── TODO: add your project endpoints here ─────────────────────────────────
// void handleSensorRead() {{ ... }}

void setup() {{
  Serial.begin(115200);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  uint32_t t = millis();
  while (WiFi.status() != WL_CONNECTED && millis()-t < WIFI_TIMEOUT_MS) delay(200);

  WiFi.mode(WIFI_STA);
  nodeId = deriveNodeId();
  Serial.printf("Node ID: %s  IP: %s\\n", nodeId.c_str(), WiFi.localIP().toString().c_str());

  MDNS.begin(nodeId.c_str());
  MDNS.addService("_ESPAI-node", "_tcp", 80);

  server.on("/api/manifest", HTTP_GET,  handleManifest);
  server.on("/api/status",   HTTP_GET,  handleStatus);
  server.on("/api/reboot",   HTTP_POST, [](){{ JsonDocument d; d["status"]="rebooting"; String b; serializeJson(d,b); server.send(200,"application/json",b); delay(200); ESP.restart(); }});
  // TODO: register your project endpoints
  // server.on("/api/sensor", HTTP_GET, handleSensorRead);
  server.begin();
}}

void loop() {{
  server.handleClient();
  delay(1);
}}
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_slug(name: str) -> str:
    slug = _SAFE_NAME.sub("", name).strip().lower()
    return slug.replace(" ", "-")[:40] or "project"


def _create_project_folder(project_id: str, name: str, description: str | None) -> None:
    node_name = _safe_slug(name)
    proj_dir  = PROJECTS_DIR / project_id
    fw_dir    = proj_dir / "firmware" / "src"
    fw_dir.mkdir(parents=True, exist_ok=True)
    (proj_dir / "workers").mkdir(exist_ok=True)
    (proj_dir / "captures").mkdir(exist_ok=True)

    # Project metadata
    meta = {
        "schema": "ESPAI.project.v1",
        "id": project_id,
        "name": name,
        "description": description or "",
        "created": _now(),
    }
    (proj_dir / ".ESPAI-project.json").write_text(
        json.dumps(meta, indent=2), encoding="utf-8"
    )

    # Human notes
    (proj_dir / "notes.md").write_text(
        f"# {name}\n\n{description or 'New ESPAI project.'}\n\n## Devices\n\n## Notes\n",
        encoding="utf-8",
    )

    # Firmware scaffold
    (fw_dir.parent / "platformio.ini").write_text(
        _PLATFORMIO_TEMPLATE.format(name=name, node_name=node_name),
        encoding="utf-8",
    )
    (fw_dir / "main.cpp").write_text(
        _MAIN_CPP_TEMPLATE.format(name=name, node_name=node_name),
        encoding="utf-8",
    )

    # Gitignore for project dir (captures are private)
    (proj_dir / ".gitignore").write_text(
        "captures/\n.pio/\n*.private.*\nsecrets.*\n", encoding="utf-8"
    )


def _row_to_dict(row) -> dict:
    d = dict(row)
    if d.get("devices"):
        try:
            d["devices"] = json.loads(d["devices"])
        except Exception:
            d["devices"] = []
    if d.get("meta"):
        try:
            d["meta"] = json.loads(d["meta"])
        except Exception:
            pass
    return d


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/")
def list_projects():
    with get_conn() as conn:
        rows = conn.execute("SELECT * FROM projects ORDER BY created DESC").fetchall()
    return [_row_to_dict(r) for r in rows]


@router.get("/{project_id}")
def get_project(project_id: str):
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
    if not row:
        raise HTTPException(404, f"Project {project_id!r} not found")
    return _row_to_dict(row)


@router.get("/{project_id}/files")
def project_files(project_id: str):
    """List files in the project directory on disk."""
    proj_dir = PROJECTS_DIR / project_id
    if not proj_dir.exists():
        return {"project_id": project_id, "files": []}
    files = []
    for f in sorted(proj_dir.rglob("*")):
        if f.is_file() and ".pio" not in str(f):
            rel = f.relative_to(proj_dir).as_posix()
            files.append({"path": rel, "size_bytes": f.stat().st_size})
    return {"project_id": project_id, "root": str(proj_dir), "files": files}


@router.post("/")
def create_project(data: ProjectCreate):
    project_id = secrets.token_hex(6)
    now = _now()
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO projects (id, name, description, devices, created) VALUES (?,?,?,?,?)",
            (project_id, data.name, data.description, json.dumps(data.devices), now),
        )
    _create_project_folder(project_id, data.name, data.description)
    return {"id": project_id, "name": data.name, "created": now}


@router.patch("/{project_id}")
def update_project(project_id: str, data: ProjectUpdate):
    updates, vals = [], []
    if data.name is not None:
        updates.append("name=?"); vals.append(data.name)
    if data.description is not None:
        updates.append("description=?"); vals.append(data.description)
    if data.devices is not None:
        updates.append("devices=?"); vals.append(json.dumps(data.devices))
    if not updates:
        return {"status": "no-op"}
    vals.append(project_id)
    with get_conn() as conn:
        if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
            raise HTTPException(404, f"Project {project_id!r} not found")
        conn.execute(f"UPDATE projects SET {', '.join(updates)} WHERE id=?", vals)
    return {"status": "updated"}


@router.delete("/{project_id}")
def delete_project(project_id: str):
    with get_conn() as conn:
        conn.execute("DELETE FROM projects WHERE id=?", (project_id,))
    return {"status": "deleted"}


# ── Project theme overrides ───────────────────────────────────────────────────

def _project_meta_path(project_id: str) -> Path:
    return PROJECTS_DIR / project_id / ".ESPAI-project.json"


def _read_project_meta(project_id: str) -> dict:
    p = _project_meta_path(project_id)
    if p.exists():
        try:
            return json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def _write_project_meta(project_id: str, meta: dict) -> None:
    p = _project_meta_path(project_id)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(meta, indent=2), encoding="utf-8")


@router.get("/{project_id}/theme")
def get_project_theme(project_id: str):
    """
    Return the merged theme token set for this project.

    Hub-level tokens are loaded from the active theme, then project-level
    overrides (stored in .ESPAI-project.json) are applied on top.
    The result is a flat dict of CSS custom property name → value.
    """
    # Load hub active theme tokens
    try:
        import yaml
        theme_path = DESIGN_DIR / "themes" / ACTIVE_THEME / "theme.yaml"
        hub_tokens: dict = {}
        if theme_path.exists():
            raw = yaml.safe_load(theme_path.read_text(encoding="utf-8")) or {}
            hub_tokens = raw.get("tokens", {})
    except Exception:
        hub_tokens = {}

    # Apply project overrides
    meta           = _read_project_meta(project_id)
    project_tokens = meta.get("theme_overrides", {})

    merged = {**hub_tokens, **project_tokens}
    return {
        "project_id":      project_id,
        "active_theme":    ACTIVE_THEME,
        "tokens":          merged,
        "project_overrides": project_tokens,
    }


@router.put("/{project_id}/theme")
def set_project_theme(project_id: str, data: ProjectThemePatch):
    """
    Save project-level theme override tokens to .ESPAI-project.json.
    Pass an empty dict to clear all overrides.
    """
    with get_conn() as conn:
        if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
            raise HTTPException(404, f"Project {project_id!r} not found")
    meta = _read_project_meta(project_id)
    meta["theme_overrides"] = data.theme_overrides
    _write_project_meta(project_id, meta)
    return {"status": "saved", "project_id": project_id, "theme_overrides": data.theme_overrides}
