import hashlib
import json
import re
import secrets
import shutil
from datetime import datetime, timezone
from pathlib import Path

import mimetypes

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse
from pydantic import BaseModel, field_validator

from ..config import ACTIVE_THEME, DESIGN_DIR, FIRMWARE_CATALOG_DIR, PROJECTS_DIR
from ..db import get_conn, _to_hostname

router = APIRouter()

_SAFE_NAME = re.compile(r"[^\w\s\-\.]")  # strip unsafe chars from folder names


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class ProjectCreate(BaseModel):
    name: str
    description: str | None = None
    devices: list[str] = []

    @field_validator("name")
    @classmethod
    def name_is_valid_hostname(cls, v: str) -> str:
        """
        Project names double as mDNS hostnames — coerce to hostname-safe form
        on the way in so every downstream user (firmware, proxy URL, Caddy)
        gets a consistent slug without extra conversion.
        """
        slug = _to_hostname(v.strip())
        if not slug:
            raise ValueError("Name must contain at least one letter or digit")
        return slug


class ProjectUpdate(BaseModel):
    name: str | None = None
    description: str | None = None
    devices: list[str] | None = None


class ProjectThemePatch(BaseModel):
    theme_overrides: dict = {}   # CSS custom property name → value


class ProjectImport(BaseModel):
    source_path: str
    name: str
    description: str | None = None


# ── Firmware template written into each new project ──────────────────────────

_PLATFORMIO_TEMPLATE = """\
; {name} — ESPAI Project Firmware
; Set WIFI credentials via environment variables before building:
;   $env:ESPAI_WIFI_SSID = "MyNetwork"
;   $env:ESPAI_WIFI_PASS = "mypassword"

[platformio]
default_envs = esp32dev

[env]
framework    = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.0
build_flags =
  -D FW_VERSION=\"0.1.0\"
  -D NODE_NAME=\"{node_name}\"
  -D WIFI_SSID=\"${{sysenv.ESPAI_WIFI_SSID}}\"
  -D WIFI_PASS=\"${{sysenv.ESPAI_WIFI_PASS}}\"

[env:seeed_xiao_esp32s3]
platform = espressif32
board    = seeed_xiao_esp32s3
build_flags = ${{env.build_flags}} -D BOARD_ID=\"seeed_xiao_esp32s3\"

[env:esp32dev]
platform = espressif32
board    = esp32dev
build_flags = ${{env.build_flags}} -D BOARD_ID=\"esp32dev\"
"""

_MAIN_CPP_TEMPLATE = """\
/**
 * {name} — ESPAI Project Firmware
 *
 * Generated by ESPAI. Modify freely.
 * The node API endpoints (manifest/status/checkin/reboot/ota) are
 * inherited from the seed firmware — add your project logic below.
 */

#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <ArduinoJson.h>

#ifndef NODE_NAME
#define NODE_NAME "{node_name}"
#endif
#ifndef FW_VERSION
#define FW_VERSION "0.1.0"
#endif
#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif
#ifndef WIFI_PASS
#define WIFI_PASS ""
#endif
#ifndef BOARD_ID
#define BOARD_ID "esp32dev"
#endif

static const uint32_t WIFI_TIMEOUT_MS = 15000;

WebServer server(80);

// ── Node ID (hashed MAC) ──────────────────────────────────────────────────
#include <mbedtls/md.h>
String deriveNodeId() {{
  uint8_t mac[6], hash[32];
  WiFi.macAddress(mac);
  mbedtls_md_context_t ctx;
  mbedtls_md_init(&ctx);
  mbedtls_md_setup(&ctx, mbedtls_md_info_from_type(MBEDTLS_MD_SHA256), 0);
  mbedtls_md_starts(&ctx);
  mbedtls_md_update(&ctx, mac, 6);
  mbedtls_md_finish(&ctx, hash);
  mbedtls_md_free(&ctx);
  String id = "node-";
  for (int i = 0; i < 6; i++) {{ if (hash[i] < 0x10) id += "0"; id += String(hash[i], HEX); }}
  return id;
}}

String nodeId;

void sendJson(int code, JsonDocument& doc) {{
  String body; serializeJson(doc, body);
  server.send(code, "application/json", body);
}}

void handleManifest() {{
  JsonDocument doc;
  doc["schema"] = "ESPAI.device.v1";
  doc["id"]     = nodeId;
  doc["name"]   = NODE_NAME;
  doc["board"]  = BOARD_ID;
  doc["fw_version"] = FW_VERSION;
  JsonObject caps = doc["capabilities"].to<JsonObject>();
  caps["ota"] = true;
  sendJson(200, doc);
}}

void handleStatus() {{
  JsonDocument doc;
  doc["id"]       = nodeId;
  doc["uptime_s"] = millis() / 1000;
  doc["heap_free"]= ESP.getFreeHeap();
  doc["ip"]       = WiFi.localIP().toString();
  sendJson(200, doc);
}}

// ── TODO: add your project endpoints here ─────────────────────────────────
// void handleSensorRead() {{ ... }}

void setup() {{
  Serial.begin(115200);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  uint32_t t = millis();
  while (WiFi.status() != WL_CONNECTED && millis()-t < WIFI_TIMEOUT_MS) delay(200);

  WiFi.mode(WIFI_STA);
  nodeId = deriveNodeId();
  Serial.printf("Node ID: %s  IP: %s\\n", nodeId.c_str(), WiFi.localIP().toString().c_str());

  MDNS.begin(nodeId.c_str());
  MDNS.addService("_ESPAI-node", "_tcp", 80);

  server.on("/api/manifest", HTTP_GET,  handleManifest);
  server.on("/api/status",   HTTP_GET,  handleStatus);
  server.on("/api/reboot",   HTTP_POST, [](){{ JsonDocument d; d["status"]="rebooting"; String b; serializeJson(d,b); server.send(200,"application/json",b); delay(200); ESP.restart(); }});
  // TODO: register your project endpoints
  // server.on("/api/sensor", HTTP_GET, handleSensorRead);
  server.begin();
}}

void loop() {{
  server.handleClient();
  delay(1);
}}
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_slug(name: str) -> str:
    """Kept for backward compatibility — delegates to the canonical _to_hostname."""
    return _to_hostname(name)


def _generate_espai_md(project_id: str, name: str, description: str | None) -> str:
    """Return the content of the per-project ESPAI.md context file."""
    node_name = _to_hostname(name)
    desc_line = description.strip() if description else "New ESPAI project."
    return f"""\
# {name} — ESPAI Project Context

> Auto-generated by ESPAI. Keep this file up to date as the project evolves.
> Agents receive this file automatically before every task prompt.

**Project ID:** `{project_id}`
**Hostname slug:** `{node_name}`
**Description:** {desc_line}

---

## Hub Integration

The ESPAI hub runs at `http://espai.local:7888/` (or `http://localhost:7888/`).

### Push sensor readings from firmware

```cpp
#include <HTTPClient.h>

void pushToHub(float value) {{
  if (WiFi.status() != WL_CONNECTED) return;
  HTTPClient http;
  http.begin("http://espai.local:7888/api/projects/{project_id}/data");
  http.addHeader("Content-Type", "application/json");
  http.addHeader("X-Device-ID", nodeId);
  http.POST("{{\"value\":" + String(value, 2) + "}}");
  http.end();
}}
```

Set `HUB_PROJECT_ID` as a build flag in `platformio.ini`:
```ini
build_flags = -D HUB_PROJECT_ID=\"{project_id}\"
```

### Read cached data from hub web app

```javascript
// Works from /app/{node_name}/ (hub) or direct device access — device can be asleep
const HUB = location.pathname.startsWith("/app/");
const HUB_API = HUB ? "" : "http://espai.local:7888";
const {{ devices }} = await fetch(HUB_API + "/api/projects/{project_id}/data/latest")
  .then(r => r.json());
// devices[0].payload → the latest reading object
```

---

## Project Structure

```
projects/{project_id}/
  firmware/              ESP32 firmware — edit freely, built with PlatformIO
    platformio.ini       Board config; set WiFi credentials via env vars
    src/main.cpp         Entry point — add project logic below the TODO comment
  web/                   Hub-hosted web app — served at /app/{node_name}/
  files/                 General project files
  captures/              Device captures (private — gitignored)
  notes.md               Project notes
  ESPAI.md               This file — project context for agents
```

---

## Firmware Quickstart

```bash
cd projects/{project_id}/firmware
pio run                  # compile only
pio run -t upload        # compile + flash via USB
pio device monitor       # open serial monitor (Ctrl+C to exit)
```

Build flags are in `platformio.ini`. WiFi credentials are injected via:
```powershell
$env:ESPAI_WIFI_SSID = "MyNetwork"
$env:ESPAI_WIFI_PASS = "mypassword"
pio run
```

---

## Key Constraints for This Project

- **Never hardcode WiFi credentials** — use `${{sysenv.ESPAI_WIFI_SSID}}` in platformio.ini
- **Never modify** `firmware/seed/` or `firmware/provision/` — they are platform templates
- **Run `pio run` and fix all errors** before committing any firmware change
- **Hub checkins are fire-and-forget** — never block the firmware loop on hub availability
- **AP fallback is required** — if WiFi fails, start `ESPAI-{{node_id_suffix}}` hotspot
- **Every hub web UI element** needs `data-tip="…"` (see CLAUDE.md)

---

## Platform Reference

- Full design spec: `docs/DESIGN_SPEC.md`
- Agent rules:      `agents/rules.md`
- Hub API docs:     `http://espai.local:7888/docs`
- Seed firmware:    `firmware/seed/src/main.cpp` (read-only reference)
"""


def _create_project_folder(project_id: str, name: str, description: str | None) -> None:
    node_name = _to_hostname(name)
    proj_dir  = PROJECTS_DIR / project_id
    fw_dir    = proj_dir / "firmware" / "src"
    fw_dir.mkdir(parents=True, exist_ok=True)
    (proj_dir / "workers").mkdir(exist_ok=True)
    (proj_dir / "captures").mkdir(exist_ok=True)

    # Project metadata
    meta = {
        "schema": "ESPAI.project.v1",
        "id": project_id,
        "name": name,
        "description": description or "",
        "created": _now(),
    }
    (proj_dir / ".ESPAI-project.json").write_text(
        json.dumps(meta, indent=2), encoding="utf-8"
    )

    # Human notes
    (proj_dir / "notes.md").write_text(
        f"# {name}\n\n{description or 'New ESPAI project.'}\n\n## Devices\n\n## Notes\n",
        encoding="utf-8",
    )

    # Firmware scaffold
    (fw_dir.parent / "platformio.ini").write_text(
        _PLATFORMIO_TEMPLATE.format(name=name, node_name=node_name),
        encoding="utf-8",
    )
    (fw_dir / "main.cpp").write_text(
        _MAIN_CPP_TEMPLATE.format(name=name, node_name=node_name),
        encoding="utf-8",
    )

    # Gitignore for project dir (captures are private)
    (proj_dir / ".gitignore").write_text(
        "captures/\n.pio/\n*.private.*\nsecrets.*\n", encoding="utf-8"
    )

    # Per-project context file — read by agents before every task
    (proj_dir / "ESPAI.md").write_text(
        _generate_espai_md(project_id, name, description), encoding="utf-8"
    )


def _row_to_dict(row) -> dict:
    d = dict(row)
    if d.get("devices"):
        try:
            d["devices"] = json.loads(d["devices"])
        except Exception:
            d["devices"] = []
    if d.get("meta"):
        try:
            d["meta"] = json.loads(d["meta"])
        except Exception:
            pass
    return d


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/")
def list_projects():
    with get_conn() as conn:
        rows = conn.execute("SELECT * FROM projects ORDER BY created DESC").fetchall()
    return [_row_to_dict(r) for r in rows]


@router.get("/{project_id}")
def get_project(project_id: str):
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
    if not row:
        raise HTTPException(404, f"Project {project_id!r} not found")
    return _row_to_dict(row)


@router.get("/{project_id}/app-url")
def project_app_url(project_id: str, request: Request):
    """
    Return the best URL to open the project's web interface.
    Priority: hub-hosted web app > linked device IP > mDNS slug.
    """
    proj_dir = PROJECTS_DIR / project_id
    if not proj_dir.exists():
        raise HTTPException(404, f"Project {project_id!r} not found")

    # Hub-hosted web app? Use slug URL for Caddy-friendliness.
    if (proj_dir / "web" / "index.html").exists():
        base = str(request.base_url).rstrip("/")
        with get_conn() as conn:
            name = conn.execute("SELECT name FROM projects WHERE id=?", (project_id,)).fetchone()
        slug = _safe_slug(name["name"]) if name else project_id
        return {"url": f"{base}/app/{slug}/", "host": "hub", "slug": slug, "project_id": project_id}

    # Linked device IP?
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
    if row:
        dev_ids = json.loads(row["devices"] or "[]")
        for did in dev_ids:
            with get_conn() as conn:
                dev = conn.execute("SELECT ip FROM devices WHERE id=?", (did,)).fetchone()
            if dev and dev["ip"]:
                return {"url": f"http://{dev['ip']}/", "host": "device"}

    # mDNS slug from project name
    with get_conn() as conn:
        row = conn.execute("SELECT name FROM projects WHERE id=?", (project_id,)).fetchone()
    if row:
        slug = _safe_slug(row["name"])
        return {"url": f"http://{slug}.local/", "host": "mdns"}

    return {"url": None, "host": None}


@router.get("/{project_id}/files")
def project_files(project_id: str):
    """List files in the project directory on disk."""
    proj_dir = PROJECTS_DIR / project_id
    if not proj_dir.exists():
        return {"project_id": project_id, "files": []}
    files = []
    for f in sorted(proj_dir.rglob("*")):
        if f.is_file() and ".pio" not in str(f):
            rel = f.relative_to(proj_dir).as_posix()
            files.append({"path": rel, "size_bytes": f.stat().st_size})
    return {"project_id": project_id, "root": str(proj_dir), "files": files}


_IMPORT_IGNORE = shutil.ignore_patterns(".pio", ".git", "__pycache__", "*.pyc", "node_modules")

_IMPORT_SIZE_LIMIT = 200 * 1024 * 1024  # 200 MB safety cap


def _dir_size(path: Path) -> int:
    return sum(f.stat().st_size for f in path.rglob("*") if f.is_file())


@router.post("/import")
def import_project(data: ProjectImport):
    src = Path(data.source_path)
    if not src.exists():
        raise HTTPException(400, f"Path not found: {data.source_path!r}")
    if not src.is_dir():
        raise HTTPException(400, "source_path must be a directory")

    # Size guard (skip .pio which can be huge)
    copyable = [
        f for f in src.rglob("*")
        if f.is_file() and ".pio" not in f.parts and ".git" not in f.parts
    ]
    total_bytes = sum(f.stat().st_size for f in copyable)
    if total_bytes > _IMPORT_SIZE_LIMIT:
        raise HTTPException(
            400,
            f"Project is {total_bytes // 1_048_576} MB — exceeds 200 MB import limit. "
            "Run `pio run --target clean` first to remove build artifacts.",
        )

    has_pio = (src / "platformio.ini").exists()
    project_id = secrets.token_hex(6)
    now = _now()

    with get_conn() as conn:
        conn.execute(
            "INSERT INTO projects (id, name, description, devices, created) VALUES (?,?,?,?,?)",
            (project_id, data.name, data.description, json.dumps([]), now),
        )

    proj_dir = PROJECTS_DIR / project_id
    fw_dest  = proj_dir / "firmware"
    try:
        shutil.copytree(str(src), str(fw_dest), ignore=_IMPORT_IGNORE)
    except Exception as exc:
        shutil.rmtree(str(proj_dir), ignore_errors=True)
        with get_conn() as conn:
            conn.execute("DELETE FROM projects WHERE id=?", (project_id,))
        raise HTTPException(500, f"Copy failed: {exc}")

    (proj_dir / "workers").mkdir(exist_ok=True)
    (proj_dir / "captures").mkdir(exist_ok=True)

    meta = {
        "schema": "ESPAI.project.v1",
        "id": project_id,
        "name": data.name,
        "description": data.description or "",
        "created": now,
        "imported_from": str(src),
    }
    (proj_dir / ".ESPAI-project.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    notes = (
        f"# {data.name}\n\n{data.description or 'Imported project.'}\n\n"
        f"Imported from: `{src}`\n\n"
        + ("PlatformIO project detected — build with `pio run`.\n" if has_pio else "")
        + "\n## Notes\n"
    )
    (proj_dir / "notes.md").write_text(notes, encoding="utf-8")
    (proj_dir / ".gitignore").write_text("captures/\n.pio/\n*.private.*\nsecrets.*\n", encoding="utf-8")

    file_count = len(copyable)
    return {
        "id": project_id,
        "name": data.name,
        "created": now,
        "source_path": str(src),
        "file_count": file_count,
        "has_platformio": has_pio,
    }


def _ini_version(ini_path: Path) -> str:
    """Extract FW_VERSION from platformio.ini build_flags, or return '0.0.0'."""
    try:
        text = ini_path.read_text(encoding="utf-8")
        for line in text.splitlines():
            m = re.search(r'FW_VERSION\\?"([^"\\]+)\\?"', line)
            if m:
                return m.group(1)
    except Exception:
        pass
    return "0.0.0"


@router.post("/{project_id}/import-build")
def import_build(project_id: str, channel: str = "dev"):
    """
    Find the most recently compiled firmware.bin in the project's .pio/build/
    directory and register it in the OTA catalog — no file upload required.
    Run 'pio run' first to produce the binary.
    """
    proj_dir = PROJECTS_DIR / project_id
    if not proj_dir.exists():
        raise HTTPException(404, f"Project {project_id!r} not found")

    build_root = proj_dir / "firmware" / ".pio" / "build"
    if not build_root.exists():
        raise HTTPException(
            404,
            "No .pio/build directory found — run 'pio run' in the firmware folder first.",
        )

    bins = [f for f in build_root.glob("**/firmware.bin") if f.is_file()]
    if not bins:
        raise HTTPException(
            404,
            "No firmware.bin found in .pio/build — run 'pio run' first.",
        )

    # Pick the freshest binary (most recent build wins)
    latest = max(bins, key=lambda f: f.stat().st_mtime)
    board   = latest.parent.name   # env directory name = board/env identifier
    version = _ini_version(proj_dir / "firmware" / "platformio.ini")

    content = latest.read_bytes()
    if not content:
        raise HTTPException(400, "firmware.bin is empty — the build may have failed.")

    sha256 = hashlib.sha256(content).hexdigest()

    FIRMWARE_CATALOG_DIR.mkdir(parents=True, exist_ok=True)
    entry_dir = FIRMWARE_CATALOG_DIR / f"{board}-{version}"
    entry_dir.mkdir(parents=True, exist_ok=True)
    (entry_dir / "firmware.bin").write_bytes(content)

    meta = {
        "schema":     "ESPAI.firmware.v1",
        "board":      board,
        "version":    version,
        "channel":    channel,
        "filename":   "firmware.bin",
        "size_bytes": len(content),
        "sha256":     sha256,
        "uploaded":   _now(),
        "known_good": False,
        "project_id": project_id,
        "source_bin": str(latest),
    }
    (entry_dir / "firmware.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return meta


@router.post("/")
def create_project(data: ProjectCreate):
    # name is already coerced to hostname-safe form by the validator
    project_id = secrets.token_hex(6)
    slug = data.name   # validator already ran _to_hostname
    now = _now()
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO projects (id, name, description, devices, slug, created) VALUES (?,?,?,?,?,?)",
            (project_id, data.name, data.description, json.dumps(data.devices), slug, now),
        )
    _create_project_folder(project_id, data.name, data.description)
    return {"id": project_id, "name": data.name, "slug": slug, "created": now}


@router.patch("/{project_id}/rename")
def rename_project(project_id: str, data: ProjectCreate):
    """Rename a project, automatically updating the slug/hostname."""
    with get_conn() as conn:
        row = conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone()
        if not row:
            raise HTTPException(404, f"Project {project_id!r} not found")
        new_slug = _to_hostname(data.name)
        conn.execute(
            "UPDATE projects SET name=?, slug=?, updated=? WHERE id=?",
            (data.name, new_slug, _now(), project_id),
        )
    return {"id": project_id, "name": data.name, "slug": new_slug}


@router.patch("/{project_id}")
def update_project(project_id: str, data: ProjectUpdate):
    updates, vals = [], []
    if data.name is not None:
        updates.append("name=?"); vals.append(data.name)
    if data.description is not None:
        updates.append("description=?"); vals.append(data.description)
    if data.devices is not None:
        updates.append("devices=?"); vals.append(json.dumps(data.devices))
    if not updates:
        return {"status": "no-op"}
    vals.append(project_id)
    with get_conn() as conn:
        if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
            raise HTTPException(404, f"Project {project_id!r} not found")
        conn.execute(f"UPDATE projects SET {', '.join(updates)} WHERE id=?", vals)
    return {"status": "updated"}


@router.delete("/{project_id}")
def delete_project(project_id: str):
    with get_conn() as conn:
        conn.execute("DELETE FROM projects WHERE id=?", (project_id,))
    return {"status": "deleted"}


@router.post("/{project_id}/regenerate-context")
def regenerate_project_context(project_id: str):
    """Regenerate the per-project ESPAI.md context file from current project metadata."""
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM projects WHERE id=?", (project_id,)).fetchone()
    if not row:
        raise HTTPException(404, f"Project {project_id!r} not found")
    proj_dir = PROJECTS_DIR / project_id
    proj_dir.mkdir(parents=True, exist_ok=True)
    content = _generate_espai_md(project_id, row["name"], row["description"])
    (proj_dir / "ESPAI.md").write_text(content, encoding="utf-8")
    return {"status": "ok", "path": str(proj_dir / "ESPAI.md")}


# ── Project theme overrides ───────────────────────────────────────────────────

def _project_meta_path(project_id: str) -> Path:
    return PROJECTS_DIR / project_id / ".ESPAI-project.json"


def _read_project_meta(project_id: str) -> dict:
    p = _project_meta_path(project_id)
    if p.exists():
        try:
            return json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def _write_project_meta(project_id: str, meta: dict) -> None:
    p = _project_meta_path(project_id)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(meta, indent=2), encoding="utf-8")


@router.get("/{project_id}/theme")
def get_project_theme(project_id: str):
    """
    Return the merged theme token set for this project.

    Hub-level tokens are loaded from the active theme, then project-level
    overrides (stored in .ESPAI-project.json) are applied on top.
    The result is a flat dict of CSS custom property name → value.
    """
    # Load hub active theme tokens
    try:
        import yaml
        theme_path = DESIGN_DIR / "themes" / ACTIVE_THEME / "theme.yaml"
        hub_tokens: dict = {}
        if theme_path.exists():
            raw = yaml.safe_load(theme_path.read_text(encoding="utf-8")) or {}
            hub_tokens = raw.get("tokens", {})
    except Exception:
        hub_tokens = {}

    # Apply project overrides
    meta           = _read_project_meta(project_id)
    project_tokens = meta.get("theme_overrides", {})

    merged = {**hub_tokens, **project_tokens}
    return {
        "project_id":      project_id,
        "active_theme":    ACTIVE_THEME,
        "tokens":          merged,
        "project_overrides": project_tokens,
    }


@router.put("/{project_id}/theme")
def set_project_theme(project_id: str, data: ProjectThemePatch):
    """
    Save project-level theme override tokens to .ESPAI-project.json.
    Pass an empty dict to clear all overrides.
    """
    with get_conn() as conn:
        if not conn.execute("SELECT id FROM projects WHERE id=?", (project_id,)).fetchone():
            raise HTTPException(404, f"Project {project_id!r} not found")
    meta = _read_project_meta(project_id)
    meta["theme_overrides"] = data.theme_overrides
    _write_project_meta(project_id, meta)
    return {"status": "saved", "project_id": project_id, "theme_overrides": data.theme_overrides}


# ── Project public page serving ───────────────────────────────────────────────
# Serves static files from projects/{project_id}/workers/public/
# e.g. GET /api/projects/c9ac1baa9ba4/page  → workers/public/index.html

@router.get("/{project_id}/page")
@router.get("/{project_id}/page/{file_path:path}")
def serve_project_page(project_id: str, file_path: str = "index.html"):
    """Serve static files from a project's workers/public/ directory."""
    pub_dir = (PROJECTS_DIR / project_id / "workers" / "public").resolve()
    if not pub_dir.exists():
        raise HTTPException(404, "No public page found for this project")

    target = (pub_dir / file_path).resolve()
    # Guard against path traversal
    if not str(target).startswith(str(pub_dir)):
        raise HTTPException(403, "Path traversal not allowed")
    if not target.exists() or not target.is_file():
        # SPA fallback
        target = pub_dir / "index.html"
    if not target.exists():
        raise HTTPException(404, f"File not found: {file_path}")

    media_type, _ = mimetypes.guess_type(str(target))
    return FileResponse(str(target), media_type=media_type or "application/octet-stream")
